# This file contains an array of objects,
# each having sets of URLs to the equivalent article/video in separate hosting locations.
# This information is useful when mapping or converting one URL to another,
# such as when generating a version of an article to be hosted on a specific platform
---
- section: introduction
  # URLs of video locations.
  video:
    # URL on the innersourcecommons.org site.
    isc: https://innersourcecommons.org/resources/learningpath/introduction/01/
    # URL on the O'Reilly learning plarform.
    oreilly: https://learning.oreilly.com/videos/introduction-to-innersource/9781492041504/9781492041504-video321606
    # URL on YouTube.
    youtube: https://www.youtube.com/watch?v=tP6K5oF2IxQ
  article:
    # URL when used as an anchor link in a published PDF.
    anchor: ''
    # URL in GitHub.
    github: https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/introduction/01-introduction.asciidoc
    # URL on the innersourcecommons.org site.
    isc: https://innersourcecommons.org/resources/learningpath/introduction/01/
    # URL on the O'Reilly learning plarform.
    oreilly: ''
- section: introduction
  video:
    isc: https://innersourcecommons.org/resources/learningpath/introduction/02/
    oreilly: https://learning.oreilly.com/videos/introduction-to-innersource/9781492041504/9781492041504-video321607
    youtube: https://www.youtube.com/watch?v=CxsfR_n7JKI
  article:
    anchor: ''
    github: https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/introduction/02-problems-solved.asciidoc
    isc: https://innersourcecommons.org/resources/learningpath/introduction/02/
    oreilly: ''
- section: introduction
  video:
    isc: https://innersourcecommons.org/resources/learningpath/introduction/03/
    oreilly: https://learning.oreilly.com/videos/introduction-to-innersource/9781492041504/9781492041504-video321608
    youtube: https://www.youtube.com/watch?v=E6VVv9S5aKw
  article:
    anchor: ''
    github: https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/introduction/03-how-works.asciidoc
    isc: https://innersourcecommons.org/resources/learningpath/introduction/03/
    oreilly: ''
- section: introduction
  video:
    isc: https://innersourcecommons.org/resources/learningpath/introduction/04/
    oreilly: https://learning.oreilly.com/videos/introduction-to-innersource/9781492041504/9781492041504-video321609
    youtube: https://www.youtube.com/watch?v=8LErWYnMfeQ
  article:
    anchor: ''
    github: https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/introduction/04-benefits.asciidoc
    isc: https://innersourcecommons.org/resources/learningpath/introduction/04/
    oreilly: ''
- section: introduction
  video:
    isc: https://innersourcecommons.org/resources/learningpath/introduction/05/
    oreilly: https://learning.oreilly.com/videos/introduction-to-innersource/9781492041504/9781492041504-video321610
    youtube: https://www.youtube.com/watch?v=8LErWYnMfeQ
  article:
    anchor: ''
    github: https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/introduction/05-principles.asciidoc
    isc: https://innersourcecommons.org/resources/learningpath/introduction/05/
    oreilly: ''
- section: introduction
  video:
    isc: https://innersourcecommons.org/resources/learningpath/introduction/06/
    oreilly: https://learning.oreilly.com/videos/introduction-to-innersource/9781492041504/9781492041504-video321611
    youtube: https://www.youtube.com/watch?v=8LErWYnMfeQ
  article:
    anchor: ''
    github: https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/introduction/06-conclusion.asciidoc
    isc: https://innersourcecommons.org/resources/learningpath/introduction/06/
    oreilly: ''
- section: trusted committer
  video:
    isc: https://innersourcecommons.org/resources/learningpath/trusted-committer/01/
    oreilly: https://learning.oreilly.com/videos/the-trusted-committer/9781492047599/9781492047599-video323925
    youtube: https://www.youtube.com/watch?v=TKdqjkPJWNU
  article:
    anchor: ''
    github: https://github.com/InnerSourceCommons/InnerSourceLearningPath/tree/master/trusted-committer/01-introduction.asciidoc
    isc: https://innersourcecommons.org/resources/learningpath/trusted-committer/01/
    oreilly: ''
- section: trusted committer
  video:
    isc: https://innersourcecommons.org/resources/learningpath/trusted-committer/02/
    oreilly: https://learning.oreilly.com/videos/the-trusted-committer/9781492047599/9781492047599-video323926
    youtube: https://www.youtube.com/watch?v=06cVAAwgsZA
  article:
    anchor: ''
    github: https://github.com/InnerSourceCommons/InnerSourceLearningPath/tree/master/trusted-committer/02-ensuring-product-quality.asciidoc
    isc: https://innersourcecommons.org/resources/learningpath/trusted-committer/02/
    oreilly: ''
- section: trusted committer
  video:
    isc: https://innersourcecommons.org/resources/learningpath/trusted-committer/03/
    oreilly: https://learning.oreilly.com/videos/the-trusted-committer/9781492047599/9781492047599-video323927
    youtube: https://www.youtube.com/watch?v=930UIbjiXZc
  article:
    anchor: ''
    github: https://github.com/InnerSourceCommons/InnerSourceLearningPath/tree/master/trusted-committer/03-keeping-the-community-healthy.asciidoc
    isc: https://innersourcecommons.org/resources/learningpath/trusted-committer/03/
    oreilly: ''
- section: trusted committer
  video:
    isc: https://innersourcecommons.org/resources/learningpath/trusted-committer/04/
    oreilly: https://learning.oreilly.com/videos/the-trusted-committer/9781492047599/9781492047599-video323928
    youtube: https://www.youtube.com/watch?v=o7geZaX7i7I
  article:
    anchor: pass:[<a data-type="xref" href="upleveling" data-xrefstyle="chap-num-title">#upleveling</a>]
    github: https://github.com/InnerSourceCommons/InnerSourceLearningPath/tree/master/trusted-committer/04-uplevelling-community-members.asciidoc
    isc: https://innersourcecommons.org/resources/learningpath/trusted-committer/04/
    oreilly: ''
- section: trusted committer
  video:
    isc: https://innersourcecommons.org/resources/learningpath/trusted-committer/05/
    oreilly: https://learning.oreilly.com/videos/the-trusted-committer/9781492047599/9781492047599-video323929
    youtube: https://www.youtube.com/watch?v=Lnz54hlKC-I
  article:
    anchor: ''
    github: https://github.com/InnerSourceCommons/InnerSourceLearningPath/tree/master/trusted-committer/05-lowering-the-barriers-to-entry.asciidoc
    isc: https://innersourcecommons.org/resources/learningpath/trusted-committer/05/
    oreilly: ''
- section: trusted committer
  video:
    isc: https://innersourcecommons.org/resources/learningpath/trusted-committer/06/
    oreilly: https://learning.oreilly.com/videos/the-trusted-committer/9781492047599/9781492047599-video323930
    youtube: https://www.youtube.com/watch?v=ucQA8mp012Q
  article:
    anchor: pass:[<a data-type="xref" href="advocating" data-xrefstyle="chap-num-title">#advocating</a>]
    github: https://github.com/InnerSourceCommons/InnerSourceLearningPath/tree/master/trusted-committer/06-advocating-for-the-communitys-needs.asciidoc
    isc: https://innersourcecommons.org/resources/learningpath/trusted-committer/06/
    oreilly: ''
- section: trusted committer
  video:
    isc: https://innersourcecommons.org/resources/learningpath/trusted-committer/07/
    oreilly: https://learning.oreilly.com/videos/the-trusted-committer/9781492047599/9781492047599-video323931
    youtube: https://www.youtube.com/watch?v=jA1p01FEHj4
  article:
    anchor: ''
    github: https://github.com/InnerSourceCommons/InnerSourceLearningPath/tree/master/trusted-committer/07-becoming-a-trusted-committer.asciidoc
    isc: https://innersourcecommons.org/resources/learningpath/trusted-committer/07/
    oreilly: ''
- section: trusted committer
  video:
    isc: https://innersourcecommons.org/resources/learningpath/trusted-committer/08/
    oreilly: https://learning.oreilly.com/videos/the-trusted-committer/9781492047599/9781492047599-video323932
    youtube: https://www.youtube.com/watch?v=n982OcEfyQE
  article:
    anchor: ''
    github: https://github.com/InnerSourceCommons/InnerSourceLearningPath/tree/master/trusted-committer/08-conclusion.asciidoc
    isc: https://innersourcecommons.org/resources/learningpath/trusted-committer/08/
    oreilly: ''
- section: product owner
  video:
    isc: https://innersourcecommons.org/resources/learningpath/product-owner/01/
    oreilly: https://learning.oreilly.com/videos/innersource-product-owners/9781492046707/9781492046707-video325229
    youtube: https://www.youtube.com/watch?v=5DXUljspcA4
  article:
    anchor: ''
    github: https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/product-owner/01-opening-article.asciidoc
    isc: https://innersourcecommons.org/resources/learningpath/product-owner/01/
    oreilly: ''
- section: product owner
  video:
    isc: https://innersourcecommons.org/resources/learningpath/product-owner/02/
    oreilly: https://learning.oreilly.com/videos/innersource-product-owners/9781492046707/9781492046707-video325230
    youtube: https://www.youtube.com/watch?v=qCGCNGHyx9I
  article:
    anchor: ''
    github: https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/product-owner/02-how-difficult-it-is-to-be-a-middle-manager-article.asciidoc
    isc: https://innersourcecommons.org/resources/learningpath/product-owner/02/
    oreilly: ''
- section: product owner
  video:
    isc: https://innersourcecommons.org/resources/learningpath/product-owner/03/
    oreilly: https://learning.oreilly.com/videos/innersource-product-owners/9781492046707/9781492046707-video325231
    youtube: https://www.youtube.com/watch?v=CuycPf1DTVQ
  article:
    anchor: ''
    github: https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/product-owner/03-major-benefits-are-built-into-the-innersource-process-article.asciidoc
    isc: https://innersourcecommons.org/resources/learningpath/product-owner/03/
    oreilly: ''
- section: product owner
  video:
    isc: https://innersourcecommons.org/resources/learningpath/product-owner/04/
    oreilly: https://learning.oreilly.com/videos/innersource-product-owners/9781492046707/9781492046707-video325232
    youtube: https://www.youtube.com/watch?v=35Ttvq1zEAA
  article:
    anchor: ''
    github: https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/product-owner/04-new-roles-and-responsibilities-article.asciidoc
    isc: https://innersourcecommons.org/resources/learningpath/product-owner/04/
    oreilly: ''
- section: product owner
  video:
    isc: https://innersourcecommons.org/resources/learningpath/product-owner/05/
    oreilly: https://learning.oreilly.com/videos/innersource-product-owners/9781492046707/9781492046707-video325233
    youtube: https://www.youtube.com/watch?v=Wxd-SiV5NSI
  article:
    anchor: ''
    github: https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/product-owner/05-recap-takeaways-article.asciidoc
    isc: https://innersourcecommons.org/resources/learningpath/product-owner/05/
    oreilly: ''
- section: product owner
  video:
    isc: https://innersourcecommons.org/resources/learningpath/product-owner/06/
    oreilly: https://learning.oreilly.com/videos/innersource-product-owners/9781492046707/9781492046707-video325234
    youtube: https://www.youtube.com/watch?v=qMGQVvoqrzo
  article:
    anchor: ''
    github: https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/product-owner/06-closing-and-contact-article.asciidoc
    isc: https://innersourcecommons.org/resources/learningpath/product-owner/06/
    oreilly: ''
- section: contributor
  video:
    isc: https://innersourcecommons.org/resources/learningpath/contributor/01/
    oreilly: https://learning.oreilly.com/learning-paths/learning-path-the/0636920338833/0636920338802-video329499
    youtube: https://www.youtube.com/watch?v=_LNtwShi_XI
  article:
    anchor: ''
    github: https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/01-introduction-article.asciidoc
    isc: https://innersourcecommons.org/resources/learningpath/contributor/01/
    oreilly: ''
- section: contributor
  video:
    isc: https://innersourcecommons.org/resources/learningpath/contributor/02/
    oreilly: https://learning.oreilly.com/learning-paths/learning-path-the/0636920338833/0636920338802-video329500
    youtube: https://www.youtube.com/watch?v=ofzSDF9EmPU
  article:
    anchor: ''
    github: https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/02-becoming-a-contributor-article.asciidoc
    isc: https://innersourcecommons.org/resources/learningpath/contributor/02/
    oreilly: ''
- section: contributor
  video:
    isc: https://innersourcecommons.org/resources/learningpath/contributor/03/
    oreilly: https://learning.oreilly.com/learning-paths/learning-path-the/0636920338833/0636920338802-video329501
    youtube: https://www.youtube.com/watch?v=PJEAQXcCh4o
  article:
    anchor: ''
    github: https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/03-contributor-ethos-article.asciidoc
    isc: https://innersourcecommons.org/resources/learningpath/contributor/03/
    oreilly: ''
- section: contributor
  video:
    isc: https://innersourcecommons.org/resources/learningpath/contributor/04/
    oreilly: https://learning.oreilly.com/learning-paths/learning-path-the/0636920338833/0636920338802-video329502
    youtube: https://www.youtube.com/watch?v=BxemepTtPz8
  article:
    anchor: ''
    github: https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/04-mechanics-of-contributing-article.asciidoc
    isc: https://innersourcecommons.org/resources/learningpath/contributor/04/
    oreilly: ''
- section: contributor
  video:
    isc: https://innersourcecommons.org/resources/learningpath/contributor/05/
    oreilly: https://learning.oreilly.com/learning-paths/learning-path-the/0636920338833/0636920338802-video329503
    youtube: https://www.youtube.com/watch?v=6TGnjmX7zb0
  article:
    anchor: ''
    github: https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/05-benefits-of-contribution-article.asciidoc
    isc: https://innersourcecommons.org/resources/learningpath/contributor/05/
    oreilly: ''
- section: contributor
  video:
    isc: https://innersourcecommons.org/resources/learningpath/contributor/06/
    oreilly: https://learning.oreilly.com/learning-paths/learning-path-the/0636920338833/0636920338802-video329504
    youtube: https://www.youtube.com/watch?v=_DimaLMLkyk
  article:
    anchor: ''
    github: https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/06-conclusion-article.asciidoc
    isc: https://innersourcecommons.org/resources/learningpath/contributor/06/
    oreilly: ''
